#
# CriptoFEP::Grandpre
#
# This module implements the Grandpré cipher, an advanced polyalphabetic
# cipher that uses a mixed alphabet and a "progressive key" (an odometer
# cipher) to defend against standard frequency analysis.
#
package CriptoFEP::Grandpre;

# --- CORE PRAGMAS ---
# Enforce modern Perl best practices for cleaner, safer code.
use strict;
use warnings;
use utf8;

# --- MODULE IMPORTS ---
# Add the parent 'lib' directory to Perl's search path.
use lib 'lib';
# Import shared utilities: text normalization and standard alphabet mappings.
use CriptoFEP::Utils qw(normalize_text $alphabet_list_ref $alphabet_map_ref);

# --- EXPORTER CONFIGURATION ---
# Standard Perl boilerplate to allow other scripts to import this module's functions.
require Exporter;
our @ISA = qw(Exporter);
# Define which subroutines can be explicitly imported by other packages.
our @EXPORT_OK = qw(grandpre_encrypt grandpre_decrypt info);

# --- Private Helper Functions ---

=head2 _generate_key_data
 
 Internal helper function to build the 25-letter (I/J combined) mixed alphabet
 and its corresponding lookup maps based on the alphabet key.
 
 B<Parameters:>
   - $key (string): The secret key (e.g., "SECRET") used to shuffle the alphabet.
 
 B<Returns:>
   - A list containing two references:
     1. (array ref): The 25-letter shuffled alphabet.
     2. (hash ref): A map of {Letter => Position} (e.g., 'S' => 0, 'E' => 1...).
 
=cut
sub _generate_key_data {
    my ($key) = @_;
    
    # Normalize the key and combine 'J' with 'I'.
    my $norm_key = normalize_text($key);
    $norm_key =~ s/J/I/g; 
    
    # Define the 25-letter base alphabet.
    my @alphabet_25_base = ('A'..'H', 'I', 'K'..'Z'); # The base alphabet without 'J'
    my %seen;
    
    # 1. Start the new alphabet with the unique letters from the key.
    my @shuffled_alphabet = grep { !$seen{$_}++ } split //, $norm_key;
    
    # 2. Add the remaining letters from the base alphabet.
    foreach my $char (@alphabet_25_base) {
        push @shuffled_alphabet, $char unless $seen{$char};
    }
    
    # Ensure the alphabet is exactly 25 letters long.
    @shuffled_alphabet = @shuffled_alphabet[0..24];

    # Create the reverse map (Letter -> Position).
    my %pos_map; # Map: Letter -> Position (0-24)
    @pos_map{@shuffled_alphabet} = (0..24);
    
    # Return both the list (for index-to-letter) and the map (for letter-to-index).
    return (\@shuffled_alphabet, \%pos_map);
}

=head2 _get_keystream_and_alphabet
 
 Internal helper function that generates the full-length progressive keystream.
 This is the "odometer" logic of the cipher.
 
 B<Parameters:>
   - $alphabet_key (string): The key for generating the mixed alphabet.
   - $position_key (string): The initial state of the evolving key.
   - $text_len (integer): The length of the text to be encrypted/decrypted.
 
 B<Returns:>
   - A list containing three references:
     1. (string): The fully generated, text-length progressive keystream.
     2. (array ref): The 25-letter shuffled alphabet.
     3. (hash ref): The {Letter => Position} map.
 
=cut
sub _get_keystream_and_alphabet {
    my ($alphabet_key, $position_key, $text_len) = @_;

    # Generate the mixed alphabet and its position map.
    my ($key_alpha, $key_pos) = _generate_key_data($alphabet_key);
    
    # Normalize the position key (e.g., "KEY"), ensuring it also combines I/J.
    my $norm_pos_key = normalize_text($position_key);
    $norm_pos_key =~ s/J/I/g; 
    
    # We will modify this array in-place as the key "evolves".
    my @pos_key_chars = split //, $norm_pos_key;
    my $pos_key_len = scalar @pos_key_chars;
    
    my $keystream = "";
    
    # Loop for the entire length of the message.
    for (my $i = 0; $i < $text_len; $i++) {
        # Find the current key letter to use (e.g., K, E, Y, K, E, Y...)
        my $key_char_index = $i % $pos_key_len;
        my $current_key_char = $pos_key_chars[$key_char_index];
        
        # Security check: Ensure the key letter exists in our alphabet.
        unless (exists $key_pos->{$current_key_char}) {
             die "Error: Position key character '$current_key_char' is invalid " .
                 "(not in the mixed alphabet generated by '$alphabet_key').\n";
        }
        
        # 1. Add the current key character to the final keystream.
        $keystream .= $current_key_char;
        
        # 2. Find the *next* letter in the mixed alphabet (the "odometer" tick).
        my $char_pos = $key_pos->{$current_key_char};
        my $next_pos = ($char_pos + 1) % 25;
        my $next_char = $key_alpha->[$next_pos];
        
        # 3. Update the position key in memory for the *next* time this index is used.
        $pos_key_chars[$key_char_index] = $next_char;
    }
    
    # Return the generated keystream and the alphabet data.
    return ($keystream, $key_alpha, $key_pos);
}


# --- PUBLIC CIPHER SUBROUTINES ---

=head2 grandpre_encrypt
 
 Encrypts plaintext using the Grandpré cipher.
 
 B<Parameters:>
   - $plaintext (string): The plaintext to be encrypted.
   - $keys (array ref): An array ref containing [ $alphabet_key, $position_key ].
 
 B<Returns:>
   - (string): The resulting ciphertext.
 
=cut
sub grandpre_encrypt {
    my ($plaintext, $keys) = @_;
    my ($alphabet_key, $position_key) = @$keys;
    
    # Normalize plaintext, combining I/J.
    my $norm_plain = normalize_text($plaintext);
    $norm_plain =~ s/J/I/g;
    
    # Pre-generate the entire progressive keystream.
    my ($keystream, $key_alpha, $key_pos) = _get_keystream_and_alphabet($alphabet_key, $position_key, length($norm_plain));
    
    my $ciphertext = "";
    my @plain_chars = split //, $norm_plain;
    my @key_chars = split //, $keystream;
    
    # Perform the Vigenere addition using the mixed alphabet.
    for (my $i = 0; $i < @plain_chars; $i++) {
        my $p_idx = $key_pos->{ $plain_chars[$i] };
        my $k_idx = $key_pos->{ $key_chars[$i] };
        
        # Handle invalid characters (this should be rare after normalization).
        if (not defined $p_idx or not defined $k_idx) {
            $ciphertext .= $plain_chars[$i]; 
            next;
        }
        
        # Apply the Vigenere formula: (P + K) mod 25
        my $c_idx = ($p_idx + $k_idx) % 25;
        $ciphertext .= $key_alpha->[$c_idx];
    }
    return $ciphertext;
}

=head2 grandpre_decrypt
 
 Decrypts ciphertext using the Grandpré cipher.
 
 B<Parameters:>
   - $ciphertext (string): The ciphertext to be decrypted.
   - $keys (array ref): An array ref containing [ $alphabet_key, $position_key ].
 
 B<Returns:>
   - (string): The original plaintext.
 
=cut
sub grandpre_decrypt {
    my ($ciphertext, $keys) = @_;
    my ($alphabet_key, $position_key) = @$keys;
    
    my $norm_cipher = normalize_text($ciphertext);
    $norm_cipher =~ s/J/I/g;
    
    # Re-generate the *exact same* progressive keystream that was used to encrypt.
    my ($keystream, $key_alpha, $key_pos) = _get_keystream_and_alphabet($alphabet_key, $position_key, length($norm_cipher));

    my $plaintext = "";
    my @cipher_chars = split //, $norm_cipher;
    my @key_chars = split //, $keystream;

    for (my $i = 0; $i < @cipher_chars; $i++) {
        my $c_idx = $key_pos->{ $cipher_chars[$i] };
        my $k_idx = $key_pos->{ $key_chars[$i] };
        
        if (not defined $c_idx or not defined $k_idx) {
            $plaintext .= $cipher_chars[$i];
            next;
        }
        
        # Apply the Vigenere inverse formula: (C - K) mod 25
        my $p_idx = ($c_idx - $k_idx + 25) % 25;
        $plaintext .= $key_alpha->[$p_idx];
    }
    return $plaintext;
}

=head2 info
 
 Returns a formatted string with detailed information about the Grandpré cipher.
 
=cut
sub info {
    # This is the new, comprehensive info block you requested.
    return qq(CIPHER: Grandpré Cipher

DESCRIPTION:
    A polyalphabetic substitution cipher, similar to Vigenere, but which uses
    a "progressive key" (or "odometer key") to defeat standard frequency 
    analysis. The key itself evolves during the encryption process,
    making it significantly stronger than a standard Vigenere.

MECHANISM (ENCRYPTION):
    The cipher requires two keys:
    1. Alphabet Key (e.g., -k SECRET): Used to create a 25-letter 
       mixed alphabet (I/J are combined).
    2. Position Key (e.g., -k2 KEY): Used as the *initial* state for the 
       evolving keystream.

    The encryption is a 7-step process for each letter:
    1. A 25-letter mixed alphabet is generated from the Alphabet Key.
       (e.g., "SECRET" -> SECRTABDFGHIKLMNOPQUVWXYZ)
    2. The Position Key "KEY" is used as the initial keystream.
    3. The first plaintext letter 'A' is encrypted with the first
       keystream letter 'K' using Vigenere addition (mod 25) on the
       mixed alphabet.
    4. **The key evolves:** The first letter of the Position Key ('K')
       is now permanently replaced by the *next* letter in the mixed
       alphabet ('L'). The Position Key in memory becomes "LEY".
    5. The second plaintext letter 'T' is encrypted with the second
       keystream letter 'E'.
    6. **The key evolves:** 'E' is replaced by 'C' (the letter after 'E'
       in the mixed alphabet). The Position Key becomes "LCY".
    7. This "odometer" process continues for the entire message.

    Example (Keys: "SECRET", "KEY", Plaintext: "ATTACKATDAWN"):
      - Plaintext: A  T  T  A  C  K  A  T  D  A  W  N
      - Keystream: K  E  Y  L  C  Z  M  R  S  N  T  A
      - Ciphertext: P  A  C  Q  T  I  U  D  D  V  S  O

MANUAL DECRYPTION:
    Decryption is the exact reverse process.
    1. The *exact same* progressive keystream ("KEYLCZMRSNTA"...) is
       re-generated using the same two keys.
    2. The Vigenere subtraction formula is used: P = (C - K + 25) mod 25.
    
    Example: Decrypt 'P' (from "PACQ...")
    1. First letter of keystream is 'K'.
    2. Alphabet: SECRTABDFGHIKLMNOPQUVWXYZ
    3. Formula: 'P' - 'K' in the mixed alphabet.
    4. 'P' (index 17) - 'K' (index 12) = 5.
    5. The letter at index 5 in the mixed alphabet is 'A'.
    6. Decryption is successful.
);
}

# --- MODULE SUCCESS